In [14]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
df = pd.read_csv('student.csv')
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [15]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [16]:
df.duplicated().sum()

0

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [19]:
df.nunique()

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

In [26]:
print("Categories in gender variables: ", end=" ")
print(df['gender'].unique())
print("Categories in race variables: ", end=" ")
print(df['race/ethnicity'].unique())
print("Categories in lunch variables: ", end=" ")
print(df['lunch'].unique())
print("Categories in test preparation course variables: ", end=" ")
print(df['test preparation course'].unique())
print("Categories in parental level of education variables: ", end=" ")
print(df['parental level of education'].unique())

Categories in gender variables:  ['female' 'male']
Categories in race variables:  ['group B' 'group C' 'group A' 'group D' 'group E']
Categories in lunch variables:  ['standard' 'free/reduced']
Categories in test preparation course variables:  ['none' 'completed']
Categories in parental level of education variables:  ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

In [29]:
numeric = [feature for feature in df.columns if df[feature].dtype != 'O']
category = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Numeric features are:', numeric)
print('Categorical features are: ', category)

Numeric features are: ['math score', 'reading score', 'writing score']
Categorical features are:  ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

In [30]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [32]:
df['total'] = df['math score'] + df['reading score'] + df['writing score']
df['average'] = df['total'] / 3
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,total,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [34]:
math_full = df[df['math score'] == 100]['average'].count()
reading_full = df[df['reading score']== 100]['average'].count()
writing_full = df[df['writing score']== 100]['average'].count()
print(f'Number of students with full marks in math {math_full}')
print(f'Number of students with full marks in reading {reading_full}')
print(f'Number of students with full marks in writing {writing_full}')

Number of students with full marks in math 7
Number of students with full marks in reading 17
Number of students with full marks in writing 14